import type { Metadata } from "next";
import {   Roboto } from "next/font/google";
import "./globals.css";
import {Toaster} from 'sonner'
import QueryProvider from "@/services/helper/provider/QueryProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], 
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white">
        <Toaster richColors position="top-right" closeButton/>
        <QueryProvider>
        {children}
        </QueryProvider>
        </body>
    </html>
  );
}
