import type { Metadata } from "next";
import AdminSidebar from "@/layout/admin/AdminSidebar";
import AdminNavbar from "@/layout/admin/AdminNavbar";

export const metadata: Metadata = {
  title: "adminpanel",
  description: "Generated by admin",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   

     <div className="flex flex-row">
        <div className="w-[288px] h-screen sticky top-0 bg-black border-r border-[#262626]">
          <AdminSidebar />
        </div>

        <div className="flex flex-col flex-1">
          <div className="bg-[#050505] sticky top-0 h-20 z-30 border-b border-[#262626]">
            <AdminNavbar />
          </div>
          <div className="bg-[#151515] flex-1 p-3">{children}</div>
        </div>
      </div>
  );
}
