

import type { Metadata } from "next";
import UserNavbar from "../../layout/user/UserNavbar";
import UserSidebar from "@/layout/user/UserSidebar";



export const metadata: Metadata = {
  title: "userpanel",
  description: "Generated by user",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   

    <div className="relative min-h-screen bg-black text-white">
      <div className="hidden md:flex flex-row">
        <div className="w-[288px] h-screen sticky top-0 bg-black border-r border-[#262626]">
          <UserSidebar />
        </div>

        <div className="flex flex-col flex-1">
          <div className="bg-[#050505] sticky top-0 h-20 z-30 border-b border-[#262626]">
            <UserNavbar />
          </div>
          <div className="bg-[#151515]  flex-1 p-3">{children}</div>
        </div>
      </div>
      <div className="md:hidden flex flex-col">
        <div className="sticky top-0 h-16 bg-black z-40 border-b border-[#262626]">
          <UserNavbar />
        </div>

        <main className="flex-1">{children}</main>
        <UserSidebar />
      </div>
    </div>
  );
}
